### ISSUE TITLE
No clicks

### ISSUE THREAD

**Issue by jbreaker** [negamartin/abs-mouse#2]
Maybe this is just an issue with my setup or personal use case, but while the application syncs up and works fine as a mouse for moving the cursor, I can't make it "click" or do anything that simulates pressing a mouse button.  With a drawing pad either the stylus interprets what you're doing or the pad does, but is there a way to make the android app understand or send a button-press?  This may be very obvious, but it eludes me.

**Comment by kovaxis** [comment]
Sorry for being so late, but no, this app only allows you to _move_ the mouse, not click with it. I haven't worked on this for years also, so I don't think I'll be able to do it anytime soon.

You're free to implement it yourself though!
